# Generated by Django 4.2.7 on 2024-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
