# Generated by Django 4.2.7 on 2024-02-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_timesheet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
