# Generated by Django 4.2.7 on 2024-02-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_timesheet_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='duration',
            new_name='workedhour',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='description',
            field=models.CharField(blank=True, default='No message', max_length=100),
        ),
    ]
